version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    # You can add more services here, for example:
    # nginx:
    #   image: nginx:latest
    #   ports:
    #     - "80:80"
    #   volumes:
    #     - ./nginx.conf:/etc/nginx/nginx.conf
